//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid Answer_Id { get; set; }
        public System.Guid Answer_Student { get; set; }
        public System.Guid Answer_Homework { get; set; }
        public string Answer_Context { get; set; }
        public bool Answer_IsDel { get; set; }
    
        public virtual Homework Homework { get; set; }
        public virtual Student Student { get; set; }
    }
}
