//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Homeworks = new HashSet<Homework>();
            this.Notes = new HashSet<Note>();
            this.Videos = new HashSet<Video>();
        }
    
        public System.Guid Course_Id { get; set; }
        public string Course_Name { get; set; }
        public System.Guid Course_Teacher { get; set; }
        public bool Course_IsGeneral { get; set; }
        public string Course_Week { get; set; }
        public bool Course_IsOpen { get; set; }
        public string Course_DayOfWeek { get; set; }
        public System.TimeSpan Course_Time { get; set; }
        public string Course_Password { get; set; }
        public string Course_College { get; set; }
        public string Course_Major { get; set; }
        public bool Course_IsDel { get; set; }
        public bool Course_IsOffline { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Homework> Homeworks { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
