//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public Homework()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public System.Guid Homework_Id { get; set; }
        public System.Guid Homework_Course { get; set; }
        public int Homework_CourseNum { get; set; }
        public int Homework_Type { get; set; }
        public string Homework_Context { get; set; }
        public bool Homework_IsDel { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
