//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public System.Guid Note_Id { get; set; }
        public System.Guid Note_Course { get; set; }
        public System.Guid Note_Student { get; set; }
        public string Note_Context { get; set; }
        public bool Note_IsDel { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
