//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class Student
    {
        public Student()
        {
            this.Answers = new HashSet<Answer>();
            this.Notes = new HashSet<Note>();
        }
    
        public System.Guid Student_Id { get; set; }
        public string Student_StuId { get; set; }
        public string Student_Password { get; set; }
        public string Student_Email { get; set; }
        public System.Guid Student_School { get; set; }
        public string Student_Name { get; set; }
        public System.DateTime Student_StartDate { get; set; }
        public string Student_College { get; set; }
        public string Student_Class { get; set; }
        public string Student_Image { get; set; }
        public string Student_Major { get; set; }
        public bool Student_Sex { get; set; }
        public bool Student_IsDel { get; set; }

        [ScriptIgnore]
        public virtual ICollection<Answer> Answers { get; set; }
        [ScriptIgnore]
        public virtual ICollection<Note> Notes { get; set; }
        [ScriptIgnore]
        public virtual School School { get; set; }
    }
}
