//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Courses = new HashSet<Cours>();
            this.Videos = new HashSet<Video>();
        }
    
        public System.Guid Teacher_Id { get; set; }
        public string Teacher_TeaId { get; set; }
        public string Teacher_Password { get; set; }
        public string Teacher_Email { get; set; }
        public System.Guid Teacher_School { get; set; }
        public string Teacher_Name { get; set; }
        public string Teacher_College { get; set; }
        public string Teacher_Image { get; set; }
        public bool Teacher_Sex { get; set; }
        public bool Teacher_IsDel { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
