//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public System.Guid Video_Id { get; set; }
        public string Video_Major { get; set; }
        public string Video_Name { get; set; }
        public string Video_Address { get; set; }
        public System.Guid Video_Teacher { get; set; }
        public string Video_College { get; set; }
        public bool Video_IsGeneral { get; set; }
        public string Video_Password { get; set; }
        public bool Video_IsOpen { get; set; }
        public bool Video_IsDel { get; set; }
        public System.Guid Video_CourseID { get; set; }
        public int Video_SerialNumber { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
